### ISSUE TITLE
[1.18.1] I can't the place the "Filter"

### ISSUE THREAD

**Issue by pewblaze** [pcal43/copper-hopper#10]
So i tried to place an item into the hopper, but its falling straight into the chest :( Not sure why though? 
copperhopper-0.0.3+1.18.1

[latest.log](https://github.com/pcal43/copper-hopper/files/8010099/latest.log)

**Comment by pcal43** [comment]
If you put 10 cobblestone in, 9 of them will fall through but the last one will 'stick' in the item filter hopper.

Is that not what you're seeing?

**Comment by pcal43** [comment]
Oh.  Actually, I think it's probably because you're using Lithium.  Lithium completely changes the hopper code and Copper Hopper can't work with it.

**Comment by pcal43** [comment]
I'll add the conflict with Lithium to the mod metadata.

**Comment by pcal43** [comment]
the new version will warn you in the log if you're also running Lithium.  Best I can do, I'm afraid.

**Comment by pcal43** [comment]
...actually, someone on curseforge just noted that you can

> Add "mixin.block.hopper=false" (without quotes) into the "lithium.properties" config file.
> This disables the performance tweaks that Lithium applies to hoppers.

**Comment by pewblaze** [comment]
Nice! Did that, thank you 👯 Will try it out later :)
