### ISSUE TITLE
"polymer-enabled = true" does not work correctly

### ISSUE THREAD

**Issue by Dizover** [pcal43/copper-hopper#29]
After restarting the server, item filter becomes item hopper, thanks to optimizing mods, I seem to know what the problem is, the data that item filter is item filter is stored in RAM, when the player goes far enough from item filter, item filter is unloaded from RAM and becomes item hopper(thanks to optimizing mods), please fix this error and port to 1.18.2. It's not because I don't like the new version, half of the mods on my server will not have the new version for a long time...

**Comment by pcal43** [comment]
Yeah, unfortunately I'm basically dropping support for polymer.  It's just too much trouble, I don't have time, and I don't actually use it myself anymore.

If you know how to fix it and want to send me a PR, I'd be happy to take a look, though.
